server:
  port: 8082
  tomcat:
    threads:
      max: 50
      min-spare: 10
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/mbo
    username: xxx
    password: xxxxxxxxxxx
  jpa:
    hibernate:
      ddl-auto: update
  #  show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  spring:
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: my-consumer-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer